name: Build Open1722

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y meson libcmocka0 libcmocka-dev lcov
    - name: Run build_all.sh script
      run: ./build_all.sh
    - name: Run test_all.sh
      run: ./test_all.sh
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./build/main_coverage.info
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
        verbose: true
